### ISSUE TITLE
Create files from attachments

### ISSUE THREAD

**Issue by bowlesdr** [jb55/mbox-stream#2]
I can see the attachments array in the mail object but cannot find a way to create files from it.

Tried: 

<pre><code>if (mail.attachments) {
  mail.attachments.forEach(function(att) {
    var wstream = fs.createWriteStream('./attachments/' + att.generatedFileName, { flags : 'w' });
    att.stream.pipe(wstream);
  });
}</code></pre>

**Comment by jb55** [comment]
Hmm we should probably just remove [this](https://github.com/jb55/mbox-stream/blob/21a2f9213a7ba337175c20611821aa44e9eddb10/index.js#L11) and include them inline...

**Comment by bowlesdr** [comment]
Changing it to:
<code>
    return new MailParser({});
</code>

And using the following works great:

<pre><code>if (mail.attachments) {
      mail.attachments.forEach(function(att) {
        fs.writeFile('./attachments/' + att.generatedFileName, att.content, function(err) {
          if (err)
            console.error(err);
        })
      });
    }</code></pre>

**Comment by jb55** [comment]
Going to reopen this for now so I know to fix this later

**Comment by jb55** [comment]
Fixed in 414275fb03ee1999dd61e2482905ecedaef922f6
